=== bbrighttaer/iot_dmg/maapiConfig.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="m2mObjects">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="mgmtObj">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mgmtDefinition" type="mgmtDefinition"/>
                            <xs:element minOccurs="0" name="corLwm2mObj" type="mgmtDefinition"/>
                            <xs:element minOccurs="0" name="corMqtt" type="mgmtDefinition"/>
                            <xs:element name="objAttributes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="attribute">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="0" name="lwm2m">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="resID" type="xs:int"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element minOccurs="0" name="mqtt">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="resID" type="xs:int"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="onem2m">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="attrName" type="xs:string"/>
                                                                <xs:element name="op" type="allowedOp"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="dataType" type="dataType" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="protocols" type="protocols" use="required"/>
                        <xs:attribute name="className" type="xs:string" use="required"/>
                        <xs:attribute name="shortName" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mgmtcmds">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="cmdType">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="code" type="xs:short"/>
                            <xs:element name="mgmtDefinition" type="mgmtDefinition"/>
                            <xs:element minOccurs="0" name="lwm2mResId" type="xs:int"/>
                            <xs:element minOccurs="0" name="mqtt" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="byte"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="Double"/>
            <xs:enumeration value="char"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Object"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="allowedOp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RO"/>
            <xs:enumeration value="RW"/>
            <!--<xs:enumeration value="E"/>-->
            <xs:enumeration value="WO"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="mgmtDefinition">
        <xs:annotation>
            <xs:documentation>This is used for mgmtObj resource.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:integer">
            <!--  Start of oneM2M Management Object Definitions -->
            <!-- unspecified -->
            <xs:enumeration value="0"/>
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="7"/>
            <!-- firmware -->
            <xs:enumeration value="1001"/>
            <!-- software -->
            <xs:enumeration value="1002"/>
            <!-- memory -->
            <xs:enumeration value="1003"/>
            <!-- areaNwkInfo -->
            <xs:enumeration value="1004"/>
            <!-- areaNwkDeviceInfo -->
            <xs:enumeration value="1005"/>
            <!-- battery -->
            <xs:enumeration value="1006"/>
            <!-- deviceInfo -->
            <xs:enumeration value="1007"/>
            <!-- deviceCapability -->
            <xs:enumeration value="1008"/>
            <!-- reboot -->
            <xs:enumeration value="1009"/>
            <!-- eventLog -->
            <xs:enumeration value="1010"/>
            <!-- cmdhPolicy -->
            <xs:enumeration value="1011"/>
            <!-- activeCmdhPolicy -->
            <xs:enumeration value="1012"/>
            <!-- cmdhDefaults -->
            <xs:enumeration value="1013"/>
            <!-- cmdhDefEcValue -->
            <xs:enumeration value="1014"/>
            <!-- cmdhEcDefParamValues -->
            <xs:enumeration value="1015"/>
            <!-- cmdhLimits -->
            <xs:enumeration value="1016"/>
            <!-- cmdhNetworkAccessRules -->
            <xs:enumeration value="1017"/>
            <!-- cmdhNwAccessRule -->
            <xs:enumeration value="1018"/>
            <!-- cmdhBuffer -->
            <xs:enumeration value="1019"/>
            <!--  End of oneM2M Management Object Definitions -->
            <xs:enumeration value="3301"/>
            <xs:enumeration value="3302"/>
            <xs:enumeration value="3303"/>
            <xs:enumeration value="3304"/>
            <xs:enumeration value="3311"/>
            <xs:enumeration value="4400"/>
            <xs:enumeration value="4401"/>
            <xs:enumeration value="4402"/>
            <xs:enumeration value="4403"/>
            <xs:enumeration value="4404"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="protocol">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lwm2m"/>
            <xs:enumeration value="mqtt"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="protocols">
        <xs:list itemType="protocol"/>
    </xs:simpleType>
</xs:schema>

=== bbrighttaer/iot_dmg/smarthomecommands.xml
<?xml version="1.0" encoding="utf-8"?>
<mgmtcmds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="maapiConfig.xsd">
    <cmdType name="RESET_MIN_MAX_VAL">
        <code>1001</code>
        <mgmtDefinition>3301</mgmtDefinition>
        <lwm2mResId>5</lwm2mResId>
    </cmdType>
    <cmdType name="DIGITAL_INPUT_COUNTER_RESET">
        <code>1002</code>
        <mgmtDefinition>3302</mgmtDefinition>
        <lwm2mResId>2</lwm2mResId>
    </cmdType>
    <cmdType name="TEMP_RESET_MIN_MAX_VAL">
        <code>1003</code>
        <mgmtDefinition>3303</mgmtDefinition>
        <lwm2mResId>6</lwm2mResId>
    </cmdType>
    <cmdType name="HUMID_RESET_MIN_MAX_VAL">
        <code>1004</code>
        <mgmtDefinition>3304</mgmtDefinition>
        <lwm2mResId>6</lwm2mResId>
    </cmdType>
    <cmdType name="REBOOT_RESOURCE">
        <code>1005</code>
        <mgmtDefinition>1009</mgmtDefinition>
        <lwm2mResId>4</lwm2mResId>
    </cmdType>
    <cmdType name="FACTORY_RESET">
        <code>1006</code>
        <mgmtDefinition>1009</mgmtDefinition>
        <lwm2mResId>5</lwm2mResId>
    </cmdType>

    <!-- MQTT Commands -->
    <cmdType name="POWER_COLD_VAL">
        <code>4001</code>
        <mgmtDefinition>4401</mgmtDefinition>
        <mqtt>1</mqtt>
    </cmdType>
    <cmdType name="DOOR_VAL">
        <code>4002</code>
        <mgmtDefinition>4401</mgmtDefinition>
        <mqtt>4</mqtt>
    </cmdType>
    <cmdType name="HOT_WATER_VAL">
        <code>4003</code>
        <mgmtDefinition>4401</mgmtDefinition>
        <mqtt>4</mqtt>
    </cmdType>

    <cmdType name="BREW_VAL">
        <code>4004</code>
        <mgmtDefinition>4402</mgmtDefinition>
        <mqtt>1</mqtt>
    </cmdType>

    <cmdType name="AC_POWER_VAL">
        <code>4005</code>
        <mgmtDefinition>4403</mgmtDefinition>
        <mqtt>0</mqtt>
    </cmdType>
    <cmdType name="SWING_VAL">
        <code>4006</code>
        <mgmtDefinition>4403</mgmtDefinition>
        <mqtt>2</mqtt>
    </cmdType>

    <cmdType name="CONTROL_VAL">
        <code>4007</code>
        <mgmtDefinition>4404</mgmtDefinition>
        <mqtt>0</mqtt>
    </cmdType>

    <cmdType name="Factory Reset">
        <code>4008</code>
        <mgmtDefinition>4400</mgmtDefinition>
        <mqtt>4400</mqtt>
    </cmdType>
    <cmdType name="Reboot">
        <code>4009</code>
        <mgmtDefinition>4400</mgmtDefinition>
        <mqtt>4400</mqtt>
    </cmdType>
    <cmdType name="Reset_Error_Code">
        <code>4010</code>
        <mgmtDefinition>4400</mgmtDefinition>
        <mqtt>4400</mqtt>
    </cmdType>
</mgmtcmds>
